/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package quanlybancafe.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import quanlybancafe.helper.JdbcHelper;

/**
 *
 * @author minhs
 */
public class BillHistoryDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillHistoryDialog.class.getName());

    /**
     * Creates new form BillHistoryDialog
     */
    public BillHistoryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void loadInvoiceList() {
        DefaultTableModel model = (DefaultTableModel) tblInvoiceList.getModel();
        model.setRowCount(0);

        // JOIN HOA_DON với KHACH_HANG để lấy TenKH
        String sql = "SELECT h.MaHD, h.NgayLap, ISNULL(k.TenKH, N'Khách vãng lai') as TenKH, h.TongTien " +
                     "FROM HOA_DON h LEFT JOIN KHACH_HANG k ON h.MaKH = k.MaKH " +
                     "ORDER BY h.NgayLap DESC";

        try (Connection con = JdbcHelper.getConnection();
             PreparedStatement ps = con.prepareStatement(sql);
             ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("MaHD"), 
                    rs.getTimestamp("NgayLap"), 
                    rs.getNString("TenKH"), 
                    rs.getDouble("TongTien")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void loadInvoiceDetail(String maHD) {
        DefaultTableModel modelDetail = (DefaultTableModel) tblInvoiceDetail.getModel();
        modelDetail.setRowCount(0);

        String sql = "SELECT s.TenSP, c.SoLuong, c.DonGia, c.ThanhTien " +
                     "FROM Chi_Tiet_Hoa_Don c JOIN SAN_PHAM s ON c.MaSP = s.MaSP " +
                     "WHERE c.MaHD = ?";

        try (Connection con = JdbcHelper.getConnection();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setString(1, maHD);
            java.sql.ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                modelDetail.addRow(new Object[]{
                    rs.getNString("TenSP"), 
                    rs.getInt("SoLuong"), 
                    rs.getDouble("DonGia"), 
                    rs.getDouble("ThanhTien")
                });
            }

            System.out.println("Đã nạp " + modelDetail.getRowCount() + " dòng chi tiết.");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInvoiceList = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblInvoiceDetail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("LỊCH SỬ GIAO DỊCH");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        tblInvoiceList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HĐ", "Thời gian", "Khách hàng", "Tổng tiền"
            }
        ));
        tblInvoiceList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInvoiceListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInvoiceList);

        jSplitPane1.setLeftComponent(jScrollPane1);

        tblInvoiceDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên SP", "SL", "Giá", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(tblInvoiceDetail);
        if (tblInvoiceDetail.getColumnModel().getColumnCount() > 0) {
            tblInvoiceDetail.getColumnModel().getColumn(0).setResizable(false);
        }

        jSplitPane1.setRightComponent(jScrollPane2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblInvoiceListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInvoiceListMouseClicked
        int row = tblInvoiceList.getSelectedRow();
        if (row >= 0) {
            String maHD = tblInvoiceList.getValueAt(row, 0).toString();
            System.out.println("Đang xem chi tiết hóa đơn: " + maHD);
            loadInvoiceDetail(maHD);
        }
    }//GEN-LAST:event_tblInvoiceListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                BillHistoryDialog dialog = new BillHistoryDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable tblInvoiceDetail;
    private javax.swing.JTable tblInvoiceList;
    // End of variables declaration//GEN-END:variables
}
