/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlybancafe.view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.Component;
/**
 *
 * @author minhs
 */
public class ManagerMainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManagerMainFrame.class.getName());

    private JPanel buttonPanel;
    
    private JPanel contentPanel;
    
    /**
     * Creates new form ManagerMainFrame
     */
    public ManagerMainFrame() {
        initComponents();
        this.setTitle("Quản Lý Cửa Hàng (SUPER MANAGER)");
        this.setExtendedState(MAXIMIZED_BOTH);
        initializeContainers();
    }

    private void initializeContainers() {
        getContentPane().setLayout(new BorderLayout());
        
        contentPanel = new JPanel(new BorderLayout());
        
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new java.awt.GridLayout(5, 1, 15, 15));
        
        buttonPanel.add(jButton1);
        buttonPanel.add(jButton2);
        buttonPanel.add(jButton4);
        buttonPanel.add(jButton3);
        buttonPanel.add(btnExit);
        
        contentPanel.add(buttonPanel, BorderLayout.CENTER);
        
        getContentPane().add(contentPanel, BorderLayout.CENTER);
    }
    
    private void showPanel(JPanel panel) {
        getContentPane().removeAll();
        
        JButton btnBack = new JButton("Quay lại Dashboard");
        btnBack.setPreferredSize(new Dimension(200, 30));
        btnBack.addActionListener(e -> resetToDashboard());
        
        JPanel mainDisplay = new JPanel(new BorderLayout());
        JPanel backPanel = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        backPanel.add(btnBack);
        
        mainDisplay.add(backPanel, BorderLayout.NORTH);
        mainDisplay.add(panel, BorderLayout.CENTER);
        
        getContentPane().add(mainDisplay, BorderLayout.CENTER);
        
        this.revalidate();
        this.repaint();
    }
    
    private void resetToDashboard() {
        getContentPane().removeAll();
        initializeContainers();
        getContentPane().revalidate();
        getContentPane().repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 5, 5));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("MENU");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton2.setText("STAFF");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton3.setText("STORAGE");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton4.setText("CUSTOMER");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel1.add(jButton4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        btnExit.setBackground(new java.awt.Color(255, 0, 0));
        btnExit.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(this::btnExitActionPerformed);
        getContentPane().add(btnExit, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        showPanel(new StaffPanel());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        showPanel(new MenuPanel());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        showPanel(new CustomerPanel());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        showPanel(new StoragePanel());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
            LoginFrame login = new LoginFrame();
            login.setVisible(true);
            login.setLocationRelativeTo(null);

            // 3. Đóng màn hình POS hiện tại
            this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManagerMainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
